### ISSUE TITLE
Add neutral gender

### ISSUE THREAD

**Issue by arvidjanson** [KatanaCode/genderize#3]
Another suggestion from the team here is to add a neutral gender for when the column is nil. Right now, were getting stuck with a number of `if gender.present?` to avoid the app from breaking down when we call gender.name if the gender column is nil. 

It would be awesome to have genderize return a neutral object (them instead of him etc).

**Comment by scarver2** [comment]
+1 genderize should handle nil so that methods like `gender.name` does not fail.

**Comment by Bodacious** [comment]
Absolutely - we actually came across this issue in another project just recently.

I'll add this asap

**Comment by scarver2** [comment]
@Bodacious Take a look at these two commits by @arvidjanson. He solved the handling of unknown gender.

https://github.com/forthevint/genderize/commit/e51f499c53a46254d8c3b6bb776835669529c372
https://github.com/forthevint/genderize/commit/110d57c1d72d2761f437a6daf3be0b7df1e345ff

I'm not in favor of this other commit because of performance reasons so please don't include that in the main gem. The friendly discussion is in the comments.
https://github.com/forthevint/genderize/commit/44fd276aeda25c4d8c37f28a8a338df206edfcc1

**Comment by Bodacious** [comment]
@scarver2 @arvidjanson Can you have a look at the "neutral" branch and let me know your thoughts? 

Does that break any existing behaviour in your apps?

**Comment by scarver2** [comment]
@Bodacious Thanks for the invite. In the `genderize.gemspec` can you reduce the minimum Rails version to 4.1?

**Comment by Bodacious** [comment]
I've bumped it down to 3 - that should be the minimum version to support I think.

There's not anything in the gem that would make it Rails 4 specific. I only bumped it up to make sure the test suite was working.

I'll incorporate CI soon

**Comment by didlix** [comment]
So glad to see this being done!

**Comment by didlix** [comment]
While I disagree with using his/her for neutral/unknown genders, a lot of marketing departments still want to use this. Could we pass it as an option?

**Comment by Bodacious** [comment]
You could set this in the locale files :)



Gavin Morrice / Managing Director

Katana Code Ltd

www.katanacode.com

gavin@katanacode.com

+44 7787 432 733




----------------------------------------------------------




This message is confidential and may contain privileged information. If it is not for you please inform us then delete it.




Any information in this message that does not relate to the official business of Katana Code is neither given nor endorsed by Katana Code. This e-mail does not constitute nor form part of a contract or unilateral obligation. Internet e-mails are not necessarily secure. Katana Code does not accept responsibility for changes made to this message after it was sent or viruses transmitted through this e-mail or any attachment. You should carry out your own virus checking procedure before opening any attachment to this e-mail. The e-mail and IT systems of Katana Code are subject to random monitoring and recording by or on behalf of Katana Code.




Katana Code is a trading name of Katana Code Ltd (Company No. SC410908), Registered Office: Lodge House, Priory Lane, Dunfermline KY12 7DT, +44 845 519 4329, www.katanacode.com

**Comment by didlix** [comment]
Great idea. I thought I was reading a pull request earlier, I guess this is in now!

**Comment by yangningBU** [comment]
Since this is already in the code base, can we close this issue and update the README?

**Comment by Bodacious** [comment]
@yangningBU done
